### ISSUE TITLE
frontera 目前不适用于 windows 平台，希望能在 README 中说明这点

### ISSUE THREAD

**Issue by tamt** [xsren/frontera-docs-zh_CN#7]
[https://github.com/scrapinghub/frontera/issues/282](https://github.com/scrapinghub/frontera/issues/282)

花了不少时间结果才发现，希望能声明这点，以免同行费时间。

**Comment by xsren** [comment]
不好意思，因为自己一直在MAC上运行，没注意到这点。接收你的提议。
